name : azure
on :  
  push:
    branches:
      - main
  pull_request:
    branches:
        - main
  workflow_dispatch:
    inputs:
      description: "env to deploy"
      required: true
      default : "dev"
      type : choice
      options :
           - "dev" 
           - "qa"
           - "prod"
permissions:
  id-token : write
  contents: read
jobs:
  login:
    name: az login
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6.0.2
      - name: azure login
        uses: azure/login@v3
        with:
          client-id:  "23576045-017e-4d10-8ad9-d0426599a118"
          subscription-id:  "0fe2604a-a62d-4f0c-8f57-3f547fa2291a"
          tenant-id:  "f3a7f9ec-a9ee-4582-826d-6fdd1b261016"
      - name: verify login
        shell: bash
        run: |
             echo "az login successful"
             az account show
             az group list --output table
