name: azure login
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: "Env to deploy"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - qa
          - prod

permissions:
  id-token: write
  contents: read

jobs:
  login:
    name: az login
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: "x"
          tenant-id: "z"
          subscription-id: "y"

      - name: Verify login
        run: |
          echo "az login successful"
          az account show
          az group list --output table
